import type {Metadata} from "next";
import "./globals.css";
import {Mulish} from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
const mulish = Mulish({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={mulish.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
